article: https://www.bigclown.com/doc/projects/radio-door-sensor/
video: https://www.youtube.com/watch?v=cvO_tXcAvZ8
images:
  - title:
    url: https://bigclown.sirv.com/playground-project-images/radio-door-sensor.jpg?w=800
assembly:
  - name: HARDWARIO Core Module
  - name: HARDWARIO Sensor Module
  - name: HARDWARIO Mini Battery Module
  - name: HARDWARIO Enclosure BCE103
